package corsac.software.meutreino.treino

import androidx.room.ColumnInfo
import androidx.room.ColumnInfo.TEXT
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "exercicio")
data class Exercicio(
    @PrimaryKey(autoGenerate = true)
    val id: Int,
    @ColumnInfo(name = "nome")
    val nome: String,
    @ColumnInfo(name = "grupo_muscular", typeAffinity = TEXT)
    val grupoMuscular: GrupoMuscular,
) {
    enum class Padroes(val instancia: Exercicio) {
        AGACHAMENTO_LIVRE(Exercicio(1, "Agachamento Livre", GrupoMuscular.INFERIORES)),
        AGACHAMENTO_FRONTAL(Exercicio(2, "Agachamento Frontal", GrupoMuscular.INFERIORES)),
        AGACHAMENTO_SUMO(Exercicio(3, "Agachamento Sumô", GrupoMuscular.INFERIORES)),
        AFUNDO(Exercicio(4, "Afundo", GrupoMuscular.INFERIORES)),
        LEG_PRESS(Exercicio(5, "Leg Press", GrupoMuscular.INFERIORES)),
        CADEIRA_EXTENSORA(Exercicio(6, "Cadeira Extensora", GrupoMuscular.INFERIORES)),
        FLEXORA_DEITADO(Exercicio(7, "Flexora Deitado", GrupoMuscular.INFERIORES)),
        STIFF(Exercicio(8, "Stiff", GrupoMuscular.INFERIORES)),
        LEVANTAMENTO_TERRA(Exercicio(9, "Levantamento Terra", GrupoMuscular.INFERIORES)),
        PANTURRILHA_EM_PE(Exercicio(10, "Panturrilha em pé", GrupoMuscular.INFERIORES)),
        PANTURRILHA_SENTADO(Exercicio(11, "Panturrilha sentado", GrupoMuscular.INFERIORES)),
        SALTO_COM_CAIXA(Exercicio(12, "Salto com Caixa", GrupoMuscular.INFERIORES)),
        PASSADAS_LONGAS(Exercicio(13, "Passadas Longas", GrupoMuscular.INFERIORES)),
        ELEVACAO_PELVICA(Exercicio(14, "Elevação Pélvica", GrupoMuscular.INFERIORES)),
        CADEIRA_ABDUTORA(Exercicio(15, "Cadeira Abdutora", GrupoMuscular.INFERIORES)),
        CADEIRA_ADUTORA(Exercicio(16, "Cadeira Adutora", GrupoMuscular.INFERIORES)),
        STEP_UP(Exercicio(17, "Step Up", GrupoMuscular.INFERIORES)),
        AGACHAMENTO_BULGARO(Exercicio(18, "Agachamento Búlgaro", GrupoMuscular.INFERIORES)),
        CARDIO_CORRIDA(Exercicio(19, "Cárdio - Corrida", GrupoMuscular.INFERIORES)),
        CARDIO_CICLISMO(Exercicio(20, "Cárdio - Ciclismo", GrupoMuscular.INFERIORES)),
        SUPINO_RETO(Exercicio(21, "Supino Reto", GrupoMuscular.PEITORAL)),
        SUPINO_INCLINADO(Exercicio(22, "Supino Inclinado", GrupoMuscular.PEITORAL)),
        SUPINO_DECLINADO(Exercicio(23, "Supino Declinado", GrupoMuscular.PEITORAL)),
        CRUCIFIXO(Exercicio(24, "Crucifixo", GrupoMuscular.PEITORAL)),
        PULL_UP(Exercicio(25, "Pull-up", GrupoMuscular.SUPERIORES)),
        BARRA_FIXA(Exercicio(26, "Barra Fixa", GrupoMuscular.SUPERIORES)),
        REMADA_CURVADA(Exercicio(27, "Remada Curvada", GrupoMuscular.SUPERIORES)),
        PULLDOWN_POLIA_ALTA(Exercicio(28, "Pulldown na Polia Alta", GrupoMuscular.SUPERIORES)),
        DESENVOLVIMENTO_MILITAR(Exercicio(29, "Desenvolvimento Militar", GrupoMuscular.SUPERIORES)),
        ELEVACAO_LATERAL(Exercicio(30, "Elevação Lateral", GrupoMuscular.SUPERIORES)),
        ROSCA_DIRETA(Exercicio(31, "Rosca Direta", GrupoMuscular.SUPERIORES)),
        ROSCA_ALTERNADA(Exercicio(32, "Rosca Alternada", GrupoMuscular.SUPERIORES)),
        TRICEPS_PULLEY(Exercicio(33, "Tríceps Pulley", GrupoMuscular.SUPERIORES)),
        TRICEPS_TESTA(Exercicio(34, "Tríceps Testa", GrupoMuscular.SUPERIORES)),
        TRICEPS_HALTERE(Exercicio(35, "Tríceps Haltere", GrupoMuscular.SUPERIORES)),
        FLEXAO_BRACO(Exercicio(36, "Flexão de Braço", GrupoMuscular.PEITORAL)),
        ROSCA_SCOTT(Exercicio(37, "Rosca Scott", GrupoMuscular.SUPERIORES)),
        PULLDOWN_POLIA_BAIXA(Exercicio(38, "Pulldown na Polia Baixa", GrupoMuscular.SUPERIORES)),
        ROSCA_MARTELO(Exercicio(39, "Rosca Martelo", GrupoMuscular.SUPERIORES)),
        FLEXAO_BRACO_PEITORAL(Exercicio(40, "Flexão de Braço (Peitoral)", GrupoMuscular.PEITORAL)),
        CRUCIFIXO_MAQUINA(Exercicio(41, "Crucifixo na Máquina", GrupoMuscular.PEITORAL)),
        PULLOVER(Exercicio(42, "Pullover", GrupoMuscular.PEITORAL)),
        FLY_DECLINADO(Exercicio(43, "Fly Declinado", GrupoMuscular.PEITORAL)),
        FLY_INCLINADO(Exercicio(44, "Fly Inclinado", GrupoMuscular.PEITORAL)),
        PULLDOWN_TRIANGULO_POLIA(Exercicio(45, "Pulldown com Triângulo na Polia", GrupoMuscular.PEITORAL)),
        VOADOR(Exercicio(46, "Voador", GrupoMuscular.PEITORAL)),
        CHEST_PRESS_MAQUINA(Exercicio(47, "Chest Press", GrupoMuscular.PEITORAL)),
        LEG_PRESS_90(Exercicio(48, "Leg Press 90º", GrupoMuscular.INFERIORES)),
        LEG_PRESS_HORIZONTAL(Exercicio(49, "Leg Press Horizontal", GrupoMuscular.INFERIORES)),
        AGACHAMENTO_SMITH(Exercicio(50, "Agachamento Smith", GrupoMuscular.INFERIORES)),
        PRANCHA(Exercicio(51, "Prancha", GrupoMuscular.INFERIORES)),
        PRANCHA_LATERAL(Exercicio(52, "Prancha Lateral", GrupoMuscular.INFERIORES)),
        ABDOMINAL_INFRA(Exercicio(53, "Abdominal Infra", GrupoMuscular.INFERIORES)),
        ABDOMINAL_OBLIQUO(Exercicio(54, "Abdominal Oblíquo", GrupoMuscular.INFERIORES)),
        ABDOMINAL_SUPRA(Exercicio(55, "Abdominal Supra", GrupoMuscular.INFERIORES)),
        FLEXORA_EM_PE(Exercicio(56, "Flexora em pé", GrupoMuscular.INFERIORES)),
        FLEXORA_SENTADO(Exercicio(57, "Flexora Sentado", GrupoMuscular.INFERIORES)),
        AGACHAMENTO_HACK(Exercicio(58, "Agachamento Hack", GrupoMuscular.INFERIORES)),
        HACK_HORIZONTAL(Exercicio(59, "Hack Horizontal", GrupoMuscular.INFERIORES)),
        PANTURRILHA(Exercicio(60, "Panturrilha", GrupoMuscular.INFERIORES)),
        PUXADA_FRONTAL(Exercicio(61, "Puxada Frontal", GrupoMuscular.SUPERIORES)),
        REMADA_CAVALETE(Exercicio(62, "Remada Cavalete", GrupoMuscular.SUPERIORES)),
        REMADA_BAIXA(Exercicio(63, "Remada Baixa", GrupoMuscular.SUPERIORES)),
        REMADA_ALTA(Exercicio(64, "Remada Alta", GrupoMuscular.SUPERIORES)),
        REMADA_CAVALO(Exercicio(65, "Remada no Cavalo", GrupoMuscular.SUPERIORES)),
        VOADOR_INVERSO(Exercicio(66, "Voador Inverso", GrupoMuscular.SUPERIORES)),
        PUXADA_SUPINADA(Exercicio(67, "Puxada Supinada", GrupoMuscular.SUPERIORES)),
        PUXADA_NEUTRA(Exercicio(68, "Puxada Neutra", GrupoMuscular.SUPERIORES)),
        PUXADA_PRONADA(Exercicio(69, "Puxada Pronada", GrupoMuscular.SUPERIORES)),
        CROSSOVER_ROLDANA(Exercicio(70, "Crossover na Roldana", GrupoMuscular.SUPERIORES)),
        CROSSOVER_CORDA(Exercicio(71, "Crossover com Corda", GrupoMuscular.SUPERIORES)),
        ELEVACAO_FRONTAL(Exercicio(72, "Elevação Frontal", GrupoMuscular.SUPERIORES)),
        DESENVOLVIMENTO_COM_HALTERES(Exercicio(73, "Desenvolvimento com Halteres", GrupoMuscular.SUPERIORES)),
        DESENVOLVIMENTO_MAQUINA(Exercicio(75, "Desenvolvimento na Máquina", GrupoMuscular.SUPERIORES)),
        TRICEPS_CORDA(Exercicio(76, "Tríceps Corda", GrupoMuscular.SUPERIORES)),
    }
}