package corsac.software.meutreino.treino

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class Exercicio(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val nome: String,
    @ColumnInfo(name = "grupo_muscular", typeAffinity = ColumnInfo.TEXT)
    val grupoMuscular: GrupoMuscular,
) {
    enum class Padroes(val instancia: Exercicio) {
        AGACHAMENTO_LIVRE(Exercicio(nome = "Agachamento Livre", grupoMuscular = GrupoMuscular.INFERIORES)),
        AGACHAMENTO_FRONTAL(Exercicio(nome = "Agachamento Frontal", grupoMuscular = GrupoMuscular.INFERIORES)),
        AGACHAMENTO_SUMO(Exercicio(nome = "Agachamento Sumô", grupoMuscular = GrupoMuscular.INFERIORES)),
        AFUNDO(Exercicio(nome = "Afundo", grupoMuscular = GrupoMuscular.INFERIORES)),
        LEG_PRESS(Exercicio(nome = "Leg Press", grupoMuscular = GrupoMuscular.INFERIORES)),
        CADEIRA_EXTENSORA(Exercicio(nome = "Cadeira Extensora", grupoMuscular = GrupoMuscular.INFERIORES)),
        FLEXORA_DEITADO(Exercicio(nome = "Flexora Deitado", grupoMuscular = GrupoMuscular.INFERIORES)),
        STIFF(Exercicio(nome = "Stiff", grupoMuscular = GrupoMuscular.INFERIORES)),
        LEVANTAMENTO_TERRA(Exercicio(nome = "Levantamento Terra", grupoMuscular = GrupoMuscular.INFERIORES)),
        PANTURRILHA_EM_PE(Exercicio(nome = "Panturrilha em pé", grupoMuscular = GrupoMuscular.INFERIORES)),
        PANTURRILHA_SENTADO(Exercicio(nome = "Panturrilha sentado", grupoMuscular = GrupoMuscular.INFERIORES)),
        SALTO_COM_CAIXA(Exercicio(nome = "Salto com Caixa", grupoMuscular = GrupoMuscular.INFERIORES)),
        PASSADAS_LONGAS(Exercicio(nome = "Passadas Longas", grupoMuscular = GrupoMuscular.INFERIORES)),
        ELEVACAO_PELVICA(Exercicio(nome = "Elevação Pélvica", grupoMuscular = GrupoMuscular.INFERIORES)),
        CADEIRA_ABDUTORA(Exercicio(nome = "Cadeira Abdutora", grupoMuscular = GrupoMuscular.INFERIORES)),
        CADEIRA_ADUTORA(Exercicio(nome = "Cadeira Adutora", grupoMuscular = GrupoMuscular.INFERIORES)),
        STEP_UP(Exercicio(nome = "Step Up", grupoMuscular = GrupoMuscular.INFERIORES)),
        AGACHAMENTO_BULGARO(Exercicio(nome = "Agachamento Búlgaro", grupoMuscular = GrupoMuscular.INFERIORES)),
        CARDIO_CORRIDA(Exercicio(nome = "Cárdio - Corrida", grupoMuscular = GrupoMuscular.INFERIORES)),
        CARDIO_CICLISMO(Exercicio(nome = "Cárdio - Ciclismo", grupoMuscular = GrupoMuscular.INFERIORES)),
        SUPINO_RETO(Exercicio(nome = "Supino Reto", grupoMuscular = GrupoMuscular.PEITORAL)),
        SUPINO_INCLINADO(Exercicio(nome = "Supino Inclinado", grupoMuscular = GrupoMuscular.PEITORAL)),
        SUPINO_DECLINADO(Exercicio(nome = "Supino Declinado", grupoMuscular = GrupoMuscular.PEITORAL)),
        CRUCIFIXO(Exercicio(nome = "Crucifixo", grupoMuscular = GrupoMuscular.PEITORAL)),
        PULL_UP(Exercicio(nome = "Pull-up", grupoMuscular = GrupoMuscular.SUPERIORES)),
        BARRA_FIXA(Exercicio(nome = "Barra Fixa", grupoMuscular = GrupoMuscular.SUPERIORES)),
        REMADA_CURVADA(Exercicio(nome = "Remada Curvada", grupoMuscular = GrupoMuscular.SUPERIORES)),
        PULLDOWN_POLIA_ALTA(Exercicio(nome = "Pulldown na Polia Alta", grupoMuscular = GrupoMuscular.SUPERIORES)),
        DESENVOLVIMENTO_MILITAR(Exercicio(nome = "Desenvolvimento Militar", grupoMuscular = GrupoMuscular.SUPERIORES)),
        ELEVACAO_LATERAL(Exercicio(nome = "Elevação Lateral", grupoMuscular = GrupoMuscular.SUPERIORES)),
        ROSCA_DIRETA(Exercicio(nome = "Rosca Direta", grupoMuscular = GrupoMuscular.SUPERIORES)),
        ROSCA_ALTERNADA(Exercicio(nome = "Rosca Alternada", grupoMuscular = GrupoMuscular.SUPERIORES)),
        TRICEPS_PULLEY(Exercicio(nome = "Tríceps Pulley", grupoMuscular = GrupoMuscular.SUPERIORES)),
        TRICEPS_TESTA(Exercicio(nome = "Tríceps Testa", grupoMuscular = GrupoMuscular.SUPERIORES)),
        TRICEPS_HALTERE(Exercicio(nome = "Tríceps Haltere", grupoMuscular = GrupoMuscular.SUPERIORES)),
        FLEXAO_BRACO(Exercicio(nome = "Flexão de Braço", grupoMuscular = GrupoMuscular.PEITORAL)),
        ROSCA_SCOTT(Exercicio(nome = "Rosca Scott", grupoMuscular = GrupoMuscular.SUPERIORES)),
        PULLDOWN_POLIA_BAIXA(Exercicio(nome = "Pulldown na Polia Baixa", grupoMuscular = GrupoMuscular.SUPERIORES)),
        ROSCA_MARTELO(Exercicio(nome = "Rosca Martelo", grupoMuscular = GrupoMuscular.SUPERIORES)),
        FLEXAO_BRACO_PEITORAL(Exercicio(nome = "Flexão de Braço (Peitoral)", grupoMuscular = GrupoMuscular.PEITORAL)),
        CRUCIFIXO_MAQUINA(Exercicio(nome = "Crucifixo na Máquina", grupoMuscular = GrupoMuscular.PEITORAL)),
        PULLOVER(Exercicio(nome = "Pullover", grupoMuscular = GrupoMuscular.PEITORAL)),
        FLY_DECLINADO(Exercicio(nome = "Fly Declinado", grupoMuscular = GrupoMuscular.PEITORAL)),
        FLY_INCLINADO(Exercicio(nome = "Fly Inclinado", grupoMuscular = GrupoMuscular.PEITORAL)),
        PULLDOWN_TRIANGULO_POLIA(Exercicio(nome = "Pulldown com Triângulo na Polia", grupoMuscular = GrupoMuscular.PEITORAL)),
        VOADOR(Exercicio(nome = "Voador", grupoMuscular = GrupoMuscular.PEITORAL)),
        CHEST_PRESS_MAQUINA(Exercicio(nome = "Chest Press", grupoMuscular = GrupoMuscular.PEITORAL)),
        LEG_PRESS_90(Exercicio(nome = "Leg Press 90º", grupoMuscular = GrupoMuscular.INFERIORES)),
        LEG_PRESS_HORIZONTAL(Exercicio(nome = "Leg Press Horizontal", grupoMuscular = GrupoMuscular.INFERIORES)),
        AGACHAMENTO_SMITH(Exercicio(nome = "Agachamento Smith", grupoMuscular = GrupoMuscular.INFERIORES)),
        PRANCHA(Exercicio(nome = "Prancha", grupoMuscular = GrupoMuscular.INFERIORES)),
        PRANCHA_LATERAL(Exercicio(nome = "Prancha Lateral", grupoMuscular = GrupoMuscular.INFERIORES)),
        ABDOMINAL_INFRA(Exercicio(nome = "Abdominal Infra", grupoMuscular = GrupoMuscular.INFERIORES)),
        ABDOMINAL_OBLIQUO(Exercicio(nome = "Abdominal Oblíquo", grupoMuscular = GrupoMuscular.INFERIORES)),
        ABDOMINAL_SUPRA(Exercicio(nome = "Abdominal Supra", grupoMuscular = GrupoMuscular.INFERIORES)),
        FLEXORA_EM_PE(Exercicio(nome = "Flexora em pé", grupoMuscular = GrupoMuscular.INFERIORES)),
        FLEXORA_SENTADO(Exercicio(nome = "Flexora Sentado", grupoMuscular = GrupoMuscular.INFERIORES)),
        AGACHAMENTO_HACK(Exercicio(nome = "Agachamento Hack", grupoMuscular = GrupoMuscular.INFERIORES)),
        HACK_HORIZONTAL(Exercicio(nome = "Hack Horizontal", grupoMuscular = GrupoMuscular.INFERIORES)),
        PANTURRILHA(Exercicio(nome = "Panturrilha", grupoMuscular = GrupoMuscular.INFERIORES)),
        PUXADA_FRONTAL(Exercicio(nome = "Puxada Frontal", grupoMuscular = GrupoMuscular.SUPERIORES)),
        REMADA_CAVALETE(Exercicio(nome = "Remada Cavalete", grupoMuscular = GrupoMuscular.SUPERIORES)),
        REMADA_BAIXA(Exercicio(nome = "Remada Baixa", grupoMuscular = GrupoMuscular.SUPERIORES)),
        REMADA_ALTA(Exercicio(nome = "Remada Alta", grupoMuscular = GrupoMuscular.SUPERIORES)),
        REMADA_CAVALO(Exercicio(nome = "Remada no Cavalo", grupoMuscular = GrupoMuscular.SUPERIORES)),
        VOADOR_INVERSO(Exercicio(nome = "Voador Inverso", grupoMuscular = GrupoMuscular.SUPERIORES)),
        PUXADA_SUPINADA(Exercicio(nome = "Puxada Supinada", grupoMuscular = GrupoMuscular.SUPERIORES)),
        PUXADA_NEUTRA(Exercicio(nome = "Puxada Neutra", grupoMuscular = GrupoMuscular.SUPERIORES)),
        PUXADA_PRONADA(Exercicio(nome = "Puxada Pronada", grupoMuscular = GrupoMuscular.SUPERIORES)),
        CROSSOVER_ROLDANA(Exercicio(nome = "Crossover na Roldana", grupoMuscular = GrupoMuscular.SUPERIORES)),
        CROSSOVER_CORDA(Exercicio(nome = "Crossover com Corda", grupoMuscular = GrupoMuscular.SUPERIORES)),
        ELEVACAO_FRONTAL(Exercicio(nome = "Elevação Frontal", grupoMuscular = GrupoMuscular.SUPERIORES)),
        DESENVOLVIMENTO_COM_HALTERES(Exercicio(nome = "Desenvolvimento com Halteres", grupoMuscular = GrupoMuscular.SUPERIORES)),
        DESENVOLVIMENTO_MAQUINA(Exercicio(nome = "Desenvolvimento na Máquina", grupoMuscular = GrupoMuscular.SUPERIORES)),
        TRICEPS_CORDA(Exercicio(nome = "Tríceps Corda", grupoMuscular = GrupoMuscular.SUPERIORES)),
    }
}